version: '2'

services:
  right-demo:
    image: java:8-alpine
    hostname: client
    links:
      - neo4j
    ports:
      - "8080:8080"
      - "5002:5002"
    volumes:
      - ./docker/config/right/run.sh:/demo/run.sh
      - ./docker/config/right/logback.xml:/demo/config/logback.xml
      - ./docker/config/right/application.properties:/demo/config/application.properties
      - ./oneprofile-right-demo/target/oneprofile-right-demo-fat-exec.jar:/demo/jars/app-fat-exec.jar
    working_dir: "/demo"
#      command: "java -jar /demo/jars/app-fat-exec.jar"
#      command: "java -jar /demo/jars/app-fat-exec.jar --jwt.publickey.path=/demo/config/key.pub"
    command: "/demo/run.sh 5002"

  neo4j:
    image: neo4j:latest
    hostname: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - /tmp/neo4j:/data

  mongodb:
    image: mongo:latest
    hostname: mongodb
    ports:
      - "27017:27017"

  cassandra:
    image: cassandra:latest
    hostname: cassandra
    ports:
      - "9042:9042"

  mariadb:
      image: mariadb
      restart: always
      ports:
        - "3306:3306"
      environment:
        MYSQL_ROOT_PASSWORD: secret
        MYSQL_DATABASE: right
        MYSQL_USER: oneprofile
        MYSQL_PASSWORD: secret
